version: 2

jobs:
  "test":
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          key: node_modules_{{ checksum "package-lock.json" }}
      - run:
          name: Installation of NPM dependencies
          command: npm install
      - save_cache:
          key: node_modules_{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Unit-testing
          command: npm test
      - run:
          name: Trying dev build
          command: npm run build:dev
      - run:
          name: Trying prod build
          command: npm run build

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
